config/routes.rb
SampleApp::Application.routes.draw do
  
  get "message/index"

  get "message/new"

  get "photos/new"

  get "photos/destroy"

  get "photos/create"

  get "tags/new"

  get "tags/create"

  get "tags/destroy"

  resources :photos
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :user_ac_relas, only: [:create, :destroy]
  resources :activities, only: [:new, :create, :destroy,:index]

  root to: 'static_pages#map'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy' #, via: :delete
      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/show_activity', to: 'static_pages#show_activity'
  match '/activities/:id', to: 'activities#show'
  match '/map', to: 'static_pages#map'
  match '/login', to: 'static_pages#login'
  match '/register', to: 'static_pages#register'
  match '/user_setting', to: 'static_pages#setting'
  match '/message/index', to: 'message#index', via: :get 
  match '/message/new', to: 'message#create', via: :post
  match '/show_all', to: 'static_pages#show_all'
  match '/show_act', to: 'static_pages#show_act'
  match '/comment', to: 'static_pages#comment'
  match '/get_all_comments', to: 'static_pages#get_all_comments'
  match '/search', to:'activities#serach_by_title_or_content'
  match '/picture_new', to: 'static_pages#picture_new'
  match '/act_photo', to: 'static_pages#act_photo'

end

app/controllers/static_pages_controller.rb
# coding = utf-8
class StaticPagesController < ApplicationController
  require 'net/http'
  require 'json'
	before_filter :signed_in_user,:except => [:login,:register]
	respond_to :html, :js, :json
  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
  
  def help
  end

  def about
    
  end

  def contact
  end

  def show_activity
    if signed_in?
      @tags = Tag.get_tags
      @activity  = current_user.activities.build
      # @feed_items = current_user.feed_for_activity.paginate(page: params[:page])
      @activities = current_user.feed_for_activity.paginate(page: params[:page])
    end
  end

  def map
    signed_in_user
    # @activity = current_user.activities.build
    # @activities = current_user.feed_for_activity.paginate(page: params[:page])
    @current_user = current_user
    @host_ip = local_ip
  end

  def login
    
  end
  
  def register
    @user = User.new
  end
  
  def setting
    @user = current_user
  end
  
  def show_all
    @user = current_user
    @joined_acts = @user.followed_acts.limit(10)
    @owned_acts = @user.activities.limit(10)
    # 开始取用户评论，首先取用户创建的活动的有关评论
    @own_acts_comments = Array.new
    @user.activities.each do |act|
      act.microposts.each do |micropost|
        micro_hash = Hash.new
        micro_hash[:id] = micropost.id
        micro_hash[:user] = micropost.user
        micro_hash[:act_title] = act.title
        micro_hash[:content] = micropost.content
        micro_hash[:created_date] = micropost.created_at
        micro_hash[:type] = "“#{micropost.user.name}”对你创建的活动“#{act.title}”说："
        @own_acts_comments << micro_hash
      end
    end
    
    #然后取用户参加活动的评论
    @joined_acts_comments = Array.new
    @user.followed_acts.each do |act|
      act.microposts.each do |micropost|
        micro_hash = Hash.new
        micro_hash[:id] = micropost.id
        micro_hash[:user] = micropost.user
        micro_hash[:act_title] = act.title
        micro_hash[:content] = micropost.content
        micro_hash[:created_date] = micropost.created_at.to_s(:due_time)
        micro_hash[:type] = "“#{micropost.user.name}”对你参加的活动“#{act.title}”说："
        @joined_acts_comments << micro_hash
      end
    end
    
    #然后去用户关注的好友的评论
    @followed_user_comments = Array.new
    @user.followed_users.each do |followed_user|
      followed_user.microposts.each do |micropost|
        micro_hash = Hash.new
        micro_hash[:id] = micropost.id
        micro_hash[:user] = micropost.user
        if micropost.activity_id
          micro_hash[:act_title] = Activity.find(micropost.activity_id).title
        end
        micro_hash[:content] = micropost.content
        micro_hash[:created_date] = micropost.created_at.to_s(:due_time)
        micro_hash[:type] = "你的好友“#{followed_user.name}”说："
        micro_hash[:user_photo] = micropost.user.photo.url(:thumb)
        @followed_user_comments << micro_hash
      end
    end
    #最后将所有的评论按时间先后进行排序
    @all_comments = @own_acts_comments + @joined_acts_comments + @followed_user_comments
    @all_comments.sort_by{|c| c[:created_date]} 
    # @all_comments.reverse!
    
    
  end
  
  def show_act
    @activity = Activity.find(params[:id])
    @acts_comments = Array.new
    @user = current_user
    #get  activity microposts
    @activity.microposts.each do |micropost|
      micro_hash = Hash.new
      micro_hash[:id] = micropost.id
      micro_hash[:user] = micropost.user
      micro_hash[:act_title] = @activity.title
      micro_hash[:content] = micropost.content
      micro_hash[:created_date] = micropost.created_at.to_s(:due_time)
      micro_hash[:type] = "“#{current_user.name}”对你参加的活动“#{@activity.title}”说："
      @acts_comments << micro_hash
    end
    
    @acts_comments.sort_by{|c| c[:created_date]} 
    # @acts_comments.reverse!
  end
  
  def comment
    @micropost = current_user.microposts.build
    activity_id = params[:id].to_i
    if params[:id]
      @micropost.activity_id = params[:id]
      puts @micropost.activity_id
    end
  end
  
  def picture_new
    activity_id = params[:id].to_i
  	@activity = Activity.find(params[:id])
    @photo = @activity.photos.build
  end
  
  def act_photo
    @user = current_user
  	@activity = Activity.find(params[:id])
    @creator = @activity.creator
  end

  def jiepan
    # puts "get jiepan"
    puts params[:title]
  end
  
  def get_all_comments
    @user = current_user
    @joined_acts = @user.followed_acts.limit(10)
    @owned_acts = @user.activities.limit(10)
    # 开始取用户评论，首先取用户创建的活动的有关评论
    @own_acts_comments = Array.new
    @user.activities.each do |act|
      act.microposts.each do |micropost|
        micro_hash = Hash.new
        micro_hash[:id] = micropost.id
        micro_hash[:user] = micropost.user.name
        micro_hash[:act_title] = act.title
        micro_hash[:content] = micropost.content
        micro_hash[:created_date] = micropost.created_at
        micro_hash[:type] = "对你创建的活动"
        @own_acts_comments << micro_hash
      end
    end
    
    #然后取用户参加活动的评论
    @joined_acts_comments = Array.new
    @user.followed_acts.each do |act|
      act.microposts.each do |micropost|
        micro_hash = Hash.new
        micro_hash[:id] = micropost.id
        micro_hash[:user] = micropost.user.name
        micro_hash[:act_title] = act.title
        micro_hash[:content] = micropost.content
        micro_hash[:created_date] = micropost.created_at
        micro_hash[:type] = "对你参加的活动"
        @joined_acts_comments << micro_hash
      end
    end
    
    #然后去用户关注的好友的评论
    @followed_user_comments = Array.new
    @user.followed_users.each do |followed_user|
      followed_user.microposts.each do |micropost|
        micro_hash = Hash.new
        micro_hash[:id] = micropost.id
        micro_hash[:user] = micropost.user.name
        if micropost.activity_id
          micro_hash[:act_title] = Activity.find(micropost.activity_id).title
        end
        micro_hash[:content] = micropost.content
        micro_hash[:created_date] = micropost.created_at
        micro_hash[:type] = "你的好友说"
        @followed_user_comments << micro_hash
      end
    end
    #最后将所有的评论按时间先后进行排序
    @all_comments = @own_acts_comments + @joined_acts_comments + @followed_user_comments
    @all_comments.sort_by{|c| c[:created_date]}
    
    respond_to do |format|
      format.json { render :json => @all_comments }
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_activity.html.erb
<li>
	<%= link_to(truncate(activity.title, :length => 100), show_act_path+"/#{activity.id}", :title => activity.title) %>
	<br>
  开始时间:
  <span class="content"><%= activity.time_start %></span>
  结束时间:
  <span class="content"><%= activity.time_end %></span>
  活动地点:
  <span class="content"><%= activity.GUID %></span>

  <span class="content"><%= activity.content %></span>
 	<span class="timestamp">
    	Posted <%= time_ago_in_words(activity.created_at) %> ago.
  	</span>
  	<% if current_user?(activity.user) %>
    	<%= link_to "delete", activities_path+"/#{activity.id}", method: :delete,
                                     data: { confirm: 'You sure?' },
                                     title: activity.content %>
  	<% end %>
</li>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="span8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>欢迎来到乐聚</h1><br>
    <h2>一个帮你为你组织活动，寻找活动的web应用！</h2>

    <%= link_to "现在注册", signup_path, 
                                class: "btn btn-large btn-primary" %>
    <br>
    <br><br><br>
    已有账号：<br>
    <%= link_to "登陆", signin_path, 
                                class: "btn btn-large btn-primary" %>
  </div>

<% end %>

app/views/static_pages/picture_new.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>
<title>乐聚 发布内容</title>
  <meta charset="UTF-8">
  <meta http-equiv="content-script-type" content="text/javascript">
  <meta http-equiv="content-style-type" content="text/css">

  <link type="text/css" rel="stylesheet" href="css/b.css">
  <link href="css/bootstrap.css" rel="stylesheet"/>
  <link href="css/bootstrap-responsive.css" rel="stylesheet">
  <link rel="shortcut icon" href="Pictures/favicon.ico"> 
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="Pictures/apple-touch-icon-144-precomposed.png"> 
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="Pictures/apple-touch-icon-114-precomposed.png"> 
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="Pictures/apple-touch-icon-72-precomposed.png"> 
  <link rel="apple-touch-icon-precomposed" href="Pictures/apple-touch-icon-57-precomposed.png">
  

</head>
<body class="whiteBg" style="padding-top:60px;">
  <!--
<div class="top alpha">
  <div class="topBox"><a href="http://wujb.cnodejs.net/home" title="返回首页" class="pbg plogo"></a>
    <div class="pNav"><a href="http://wujb.cnodejs.net/home" title="首页" class="pbg navHome"></a><a href="http://wujb.cnodejs.net/publish" title="发布内容" class="pbg navContent"></a><a href="http://wujb.cnodejs.net/message" title="私信" class="pbg navMsg"></a><a href="http://wujb.cnodejs.net/friends" title="好友" class="pbg navFriend"></a><a href="http://wujb.cnodejs.net/search" title="搜索" class="pbg navSearch"></a><a href="http://wujb.cnodejs.net/setting" title="设置" class="pbg navSet"></a><a href="http://wujb.cnodejs.net/home/logout" title="退出" class="pbg navLogout"></a>
      <div class="pbg pnNow pnContent"></div>
      <div class="pbg unRead"><span id="unRead"></span>
        <div class="unReadRight pbg"></div>
      </div>
    </div>
  </div>
</div>
-->

<!-- Container for an overlay: 这个div是用来做发布活动还有乐聚猜弹出的遮罩的--> 
  <div class="ow-overlay ow-closed"></div> 

  <!-- Container for a modal window: found activity 弹出发布活动的区域部分，主要就是modal这个class控制 modal_a只是我单独添的class名 就是区分一下不同modal的 其他的都是发布活动的布局还有标签--> 
  <div class="modal ow-closed well modal_a" id="id_foundactivity_container">
    <button type="button" class="btn-mini pull-right close_a-button"><i class="icon-remove"></i></button>
    <h3>&nbsp;&nbsp;发布活动</h3>
    <ul></ul>
    <ul>
      <li>活动名称<input type="text" id="activity-name-input" class="input-xlarge" placeholder="6-20个汉字" style="position:relative;left:30px;"><a style="position:relative;left:60px;">*</a></li>
      <!-- id="date-input"是日历1的特效 请见calendar.js的文件-->
      <li>活动时间<input type="text" id="date-input" class="input-xlarge" placeholder="请选择活动开始时间" style="position:relative;left:30px;"/><a style="position:relative;left:60px;">*</a></li>
      <li>活动类型<input type="text" id="activity-type-input" class="input-xlarge" placeholder="6-20个汉字" style="position:relative;left:30px;"><a style="position:relative;left:60px;">*</a></li>
      <li>活动地点<input type="text" id="activity-place-input" class="input-xlarge" placeholder="请输入活动地点" style="position:relative;left:30px;"><a style="position:relative;left:60px;">*</a></li>
      <li>活动人数<input type="text" id="activity-number-input" class="input-xlarge" placeholder="请输入活动人数" style="position:relative;left:30px;"><a style="position:relative;left:60px;">*</a></li>
      <li>邀请人员<input type="text" id="activity-people-input" class="input-xlarge" placeholder="请邀请人员参与活动" style="position:relative;left:30px;"><a style="position:relative;left:60px;">*</a></li>
      <p></p>
      <li>活动描述<textarea class="span5" name="textArea1" id="activity-description-input" cols="30" rows="2" placeholder="请对活动进行适当描述" style="position:relative;left:30px;"></textarea><a style="position:relative;left:60px;">*</a></li>
      <p></p>
      <li>备&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;注<textarea class="span5" name="textArea1" id="activity-ps-input" cols="30" rows="2" placeholder="请适当的添加备注" style="position:relative;left:30px;"></textarea></li>
      <p></p>
      <p><button type="submit" class="btn-large close_c-button" id="activity-submit" style="position:relative;left:260px;">提交</button></p>
    </ul>
    </div>

<!-- Container for a modal window: leju guess 下面这个div跟上面的基本相同，是给乐聚猜 就是活动推荐用的--> 
    <div class="modal_b ow-closed well modal" id="id_recommend_container">
    <button type="button" class="btn-mini pull-right close_b-button"><i class="icon-remove"></i></button>
    <h3>&nbsp;&nbsp;活动推荐</h3>
    <ul></ul>
    <ul>
      </br></br></br></br>
      <li>活动主题<input type="text" id="recommend-title-input" class="input-xlarge" placeholder="6-20个汉字" style="position:relative;left:30px;"><a style="position:relative;left:60px;">*</a></li>
      </br></br></br></br>
      <!-- 下面id=“demo2”就是日历2的特效-->
      <li>活动时间<input type="text" id="demo2" class="input-xlarge" placeholder="请选择活动开始时间" style="position:relative;left:30px;"/><a style="position:relative;left:60px;">*</a></li>
      </br></br></br></br>
      <p><button type="submit" class="btn-large close_d-button" id="recommend-submit" style="position:relative;left:260px;">活动推荐</button></p>
    </ul>
    </div>



<!-- fixed top bar--> 
    <div class="navbar navbar-fixed-top" id="id_topbar">
      <div class="navbar-inner"> 
        <div class="container-fluid">     
          <a class="brand" href="map.html" title="首页"> 乐 聚</a>  
          <div class="nav-collapse"> 
              <ul class="nav nav-pills">

                  <li><a href="<%=map_path%>">地  图</a>
                  </li>
                  <li class="active"><a href="<%=show_all_path%>">活  动</a></li>
              </ul>

              <ul class="nav nav-pills pull-right">
                  <li class="guess-button"><a href="#"><i class="icon-upload icon-white"></i> 活动推荐</a></li>
				<li><%= link_to "设置", user_setting_path(current_user) %></li>
                  <li><%= link_to "退出", signout_path, method: "delete" %></li>

                  <li><%= link_to "用户名:#{@current_user.name}", user_setting_path(current_user) %></li>
                    

              </ul>
                       

            <form class="nav pull-right form-search input-append">
                <input type="text" id="search1" class="input-medium search-query input-append" placeholder="搜人/新动态"><button type="submit" id="search-submit1" class="btn"><i class="icon-search"></i></button>
            </form>

            <ul class="nav nav-pills pull-right"> 
              <li class="dropdown" id="menu1">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#menu4">
              <img src="Pictures/pic1.png" title="通知和提醒">
              <b class="caret"></b>
              </a>
                <ul class="dropdown-menu">
                  <li><a href="#" id="remind1">提醒1</a></li>
                  <li><a href="#" id="remind2">提醒2</a></li>
                  <li class="divider"></li>
                  <li><a href="#" id="notice1">通知1</a></li>
                  <li><a href="#" id="notice2">通知2</a></li>
                </ul>
              </li>  
            </ul>
          </div>
        </div> 
      </div> 
    </div><!-- end fixed top bar--> 


    <!-- 这个地方就是伸缩框的部分 相关js放在了chatwindow.js的最上面，很短，其实就是直接用了jquery， $('#opciones').slideToggle(); 用这一句控制了伸缩--> 
      <DIV id=settings>Settings</DIV>
      <DIV id=opciones style="overflow:scroll;overflow-x:hidden;">
          <form class="nav form-search input-append">    
                <input type="text" id="search2" class="input-small search-query input-append" placeholder="搜人/新动态"><button type="submit" id="search-submit2" class="btn"><i class="icon-search"></i></button>
            </form>
        <table>
        <tr><td><img id="item2-pic" src="Pictures/资环学院.jpg">
          <a href="#" id="item2-name" style="color:#ff7500;position:relative;bottom:14px;">&nbsp;资源与环境学院</a> 
        </td></tr>
        <tr><td>
            <p id="item2-title">活动名称：植树在行动！</p>
          </td></tr>
          <tr><td><p id="item2-description">活动描述：植树在行动，需要您的参与！本次树苗不多，想要参加的同学尽快了！</p></td></tr>
          <tr><td>
            <p id="item2-where">活动地点:植物园</p>
          </td></tr>
          <tr><td>
            <p id="item2-when">活动时间：2012年9月20日</p>
          </td></tr>
          <tr><td>
            <p id="item2-no">活动人数：80-120</p>
          </td></tr>
        <tr><td><p id="item2-time">n天前</p>  
          <a class="pull-right" id="item2-details" onclick="ChatShow();">查看详情(220)&nbsp;&nbsp;&nbsp;</a>
        </td></tr>
      </table>

      <table>
          <tr><td></br><img id="item1-pic" src="Pictures/艺术学院.jpg"><a href="#" id="item1-name" style="color:#ff7500;position:relative;bottom:14px;">&nbsp;艺术与设计学院</a> </td>
            <tr><td>
            <p id="item1-title">活动名称：艺术节比赛报名！</p>
          </td></tr>
          <tr><td>
            <p id="item1-description">活动描述：第九届校园艺术节将于9月20日盛大开幕，本次艺术节包括了绘画比赛，海报设计大赛，K歌大赛等项目，快来报名参加吧！</p>
          </td></tr>
          <tr><td>
            <p id="item1-where">活动地点：学校</p>
          </td></tr>
          <tr><td>
            <p id="item1-when">活动时间：2012年9月20日--10月20日</p>
          </td></tr>
          <tr><td>
            <p id="item1-no">活动人数：不限</p>
          </td></tr>
        <tr><td><p id="item1-time">n天前</p>  
          <a class="pull-right" id="item1-details" onclick="ChatShow();">查看详情(3)&nbsp;&nbsp;&nbsp;</a>
        </td></tr>
      </table>
      <table>
        <tr><td></br><img id="item3-pic" src="Pictures/软件学院.jpg">
          <a href="#" id="item3-name" style="color:#ff7500;position:relative;bottom:14px;">&nbsp;软件学院</a> 
        </td></tr>
        <tr><td>
            <p id="item3-title">活动名称：C语言编程大赛！</p>
          </td></tr>
          <tr><td><p id="item3-description">活动描述：第五届C语言编程大赛火热报名啦！前10名均有奖金！</p></td></tr>
          <tr><td>
            <p id="item3-where">活动地点：软件学院实验室</p>
          </td></tr>
          <tr><td>
            <p id="item3-when">活动时间：2012年9月25日--10月10日</p>
          </td></tr>
          <tr><td>
            <p id="item3-no">活动人数：不限</p>
          </td></tr>
        <tr><td><p>n天前</p>  
          <a class="pull-right" id="item3-details" onclick="ChatShow();">查看详情(20)&nbsp;&nbsp;&nbsp;</a>
        </td></tr>
      </table>
      </DIV>

<!-- chatwindow 下面的东西是左边的聊天窗，内容也在chatwindow.js里--> 
<!-- end chatwindow-->


<div class="sBody clearfix">
  <div class="setBody clearfix">
      <%= form_for @photo,:url => photos_path,id:"publish", :html => { :multipart => true } do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>
      <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tbody>
          <tr>
            <td colspan="3" class="tabTitle"><b>发布图片</b></td>
          </tr>
          <tr>
            <td class="tabHead">选择本地图片</td>
            <td>
	             <%= f.file_field :image %>
            </td>
          </tr>
          
          <tr>
            <td class="tabHead">图片描述内容</td>
            <td colspan="2">
		        <%= f.text_area :description,id:"content", name:"content", maxlength:"300", class:"textInput textTextarea", placeholder: "关于图片的描述。。。" %>
		                  <%= hidden_field_tag "activity_id", @activity.id %>
				</td>
          </tr>
          <tr>
            <td></td>
            <td><a href="javascript:;" class="pbg comBt">
               <%= f.submit "上传图片", class: "btn btn-large" %>
            <td></td>
          </tr>
        </tbody>
      </table>
       
      <% end  %>
   
  </div>
</div>
<input id="err" value="" type="hidden">
<input id="suc" value="" type="hidden">
<div class="foot">
  <div class="footBox"><span>MileStone_42 版权所有 ©2011-2012</span><span>email: 42thcoder@gmail.com</span><span><a href="" target="_blank">本站介绍</a></span><span><a href="" target="_blank">错误和建议</a></span></div>
</div>
<script src="js/ga.js" async="" type="text/javascript"></script><script src="js/wujb_content"></script>
<div id="tip" class="baseTip"><span class="btBox"></span></div>
<script src="js/h.js" type="text/javascript"></script>
  <script type="text/javascript" src="js/jquery.js"></script>
  <script type="text/javascript" src="js/jquery.omniwindow.js"></script>
  <script type="text/javascript" src="js/calendar.js"></script>
  <script type="text/javascript" src="js/chatwindow.js"></script>
  <script type="text/javascript" src="js/normalhead.js"></script> 

    <script src="js/bootstrap-transition.js"></script> 
    <script src="js/bootstrap-alert.js"></script> 
    <script src="js/bootstrap-modal.js"></script> 
    <script src="js/bootstrap-dropdown.js"></script> 
    <script src="js/bootstrap-scrollspy.js"></script> 
    <script src="js/bootstrap-tab.js"></script> 
    <script src="js/bootstrap-tooltip.js"></script> 
    <script src="js/bootstrap-popover.js"></script> 
    <script src="js/bootstrap-button.js"></script> 
    <script src="js/bootstrap-collapse.js"></script> 
    <script src="js/bootstrap-carousel.js"></script> 
    <script src="js/bootstrap-typeahead.js"></script>  
</body>
</html>