config/routes.rb
SampleApp::Application.routes.draw do
  
  get "message/index"

  get "message/new"

  get "photos/new"

  get "photos/destroy"

  get "photos/create"

  get "tags/new"

  get "tags/create"

  get "tags/destroy"

  resources :photos
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :user_ac_relas, only: [:create, :destroy]
  resources :activities, only: [:new, :create, :destroy,:index]

  root to: 'static_pages#map'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy' #, via: :delete
      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/show_activity', to: 'static_pages#show_activity'
  match '/activities/:id', to: 'activities#show'
  match '/map', to: 'static_pages#map'
  match '/login', to: 'static_pages#login'
  match '/register', to: 'static_pages#register'
  match '/user_setting', to: 'static_pages#setting'
  match '/message/index', to: 'message#index', via: :get 
  match '/message/new', to: 'message#create', via: :post
  match '/show_all', to: 'static_pages#show_all'
  match '/show_act', to: 'static_pages#show_act'
  match '/comment', to: 'static_pages#comment'
  match '/get_all_comments', to: 'static_pages#get_all_comments'
  match '/search', to:'activities#serach_by_title_or_content'
  match '/picture_new', to: 'static_pages#picture_new'
  match '/act_photo', to: 'static_pages#act_photo'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">乐聚</a>
    by Milestone 42
  </small>
  <nav>
    <ul>
      <li><%= link_to "关于乐聚",   about_path %></li>
      <li><%= link_to "联系我们", contact_path %></li>
      <li><a href="#">新闻</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "乐聚", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "主页", root_path %></li>
          <li><%= link_to "活动", show_activity_path %></li>
          <li><%= link_to "帮助", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "所有用户", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                账户 <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "个人资料", current_user %></li>
                <li><%= link_to "设置", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "退出", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "登陆", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->